name: roboshop-reusable-actions
on:
  workflow_call:
    inputs:
      componentName:
        required: true
        type: string
jobs:
  UNIT-TESTS:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: test the application
        run: |
          echo npm install

  build:
    runs-on: self-hosted
    needs: UNIT-TESTS
    steps:
      - uses: actions/checkout@v4
      - name: build the application
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 572282991444.dkr.ecr.us-east-1.amazonaws.com
          docker build -t 572282991444.dkr.ecr.us-east-1.amazonaws.com/roboshop-${{ inputs.componentName }}:${{ github.sha }} .
          docker push 572282991444.dkr.ecr.us-east-1.amazonaws.com/roboshop-${{ inputs.componentName }}:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: build the application
        run: |
          echo npm install

  DEV:
    runs-on: self-hosted
    needs: deploy
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - name: set kube context
        run: |
          kubectl config set-context --current --namespace=argocd

      - name: login argocd
        run: |
          url=$(kubectl get svc argocd-server -n argocd -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
          argocd_password=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          argocd login $url --insecure --username admin --password $argocd_password

      - name: deploy application
        run: argocd app create ${{ inputs.componentName }} --repo https://github.com/dsaniset23/roboshop-helm.git --path . --dest-server https://kubernetes.default.svc --dest-namespace default --set COMMIT_ID=${{ github.sha }}

  QA:
    runs-on: self-hosted
    needs: DEV
    environment: QA
    steps:
      - uses: actions/checkout@v4
      - name: runs in QA env
        run: |
          echo run in QA env

  integration-testing:
    needs: QA
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: do integration testing
        run: |
          echo perform integration testing

  UAT:
    runs-on: self-hosted
    needs: QA
    environment: UAT
    steps:
      - uses: actions/checkout@v4
      - name: deploy in UAT
        run: |
          echo deploy in UAT

  prod:
    runs-on: self-hosted
    needs: UAT
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: deploy in prod
        run: |
          echo deploy in prod